### ISSUE TITLE
好友过多未全部加载

### ISSUE THREAD

**Issue by Zingy101** [wgzeyu/SCFLGT#1]
RGSC网页默认显示12名好友，剩余好友需要点击“载入更多 Load More“，但是也只能在检测开始前的几秒钟内点击，导致不能全部查完。

另一个就是浏览过快...

可以加一个暂停/继续按钮（？）

**Comment by wgzeyu** [comment]
暂时不打算更新了，之前自己用的时候临时写的，很多地方做的很差，现在也用不到了。。
比如没有检测是否载入完成，按固定间隔检测并判断是否点击载入更多，检测的时候没加载出，结果就以为加载完了...
可以先自己改一下源码，各种间隔时间调长一些
